### PR TITLE
Fix left padding for `.sig-inline`

### PR DESCRIPTION
**Pull request by marxin**
Fixes: #486

### CODE REVIEW

**Comment by marxin** [comment]
May I please ping this?

**Comment by pradyunsg** [comment]
Got a screenshot for before/after?

**Comment by marxin** [comment]
Sure, before:
Screenshot from 2022-09-20 13-01-34

and after:
Screenshot from 2022-09-20 13-01-12

**Comment by pradyunsg** [comment]
Hmm... Could we add a demo of the problematic markup in the kitchen sink? It'd serve to help avoid regressing on this front in the future.

**Comment by marxin** [comment]
Sure, here it is:

```rst
.. c:type:: my_type

This works :c:type:`my_type`, but I would like to point
to a pointer of the type (:c:expr:`my_type *`).
```

**Pull request merged**
