### PR TITLE
Run `npm install` before `npx` when building on Read the Docs

### PR DESCRIPTION
**Pull request by humitos**
Install all dependencies with `npm install` before building with gulp.

Updates from #274 that was failing due `npm install` not being called.

I'm passing `cwd` to be the root of the cloned repository when calling `npm` and `npx`.

I imported my own fork as a test on Read the Docs, but it's still failing because `furo.css` is not found in the theme installation. However, all the node commands did work. So, this may need a little more research to understand why it doesn't work yet: https://readthedocs.org/projects/furo-humitos/builds/14862163/

### CODE REVIEW

**Comment by Caglar1881** [comment]
#274

**Comment by pradyunsg** [comment]
That's because the asset generation is happening after Furo has been installed in the environment.

- Run `pip install` from the git checkout of Furo.
- Run generate the assets, as part of building the documentation, which happens *after* the project's files have been installed (without the generated files).
- Run the theme's extension, which looks for the generated files (which isn't installed, since the generated copy was created after the installation) and fails to locate it + crashes.

An editable install _may_ do the trick but that needs to wait for a pip release and a flit release; adding PEP 660 support to both of them.

Alternatively, a pre-install step on RTD would work. So would having Furo's build system generate the assets as part of the wheel generation process.

**Comment by humitos** [comment]
> That's because the asset generation is happening after Furo has been installed in the environment.

Thanks for the explanation.

> An editable install _may_ do the trick but that needs to wait for a pip release and a flit release; adding PEP 660 support to both of them.

I didn't know that `pyproject.toml` does not support `-e` yet. I did a test because I wasn't sure what you meant in this comment (I added a new commit that uses a workaround on Read the Docs to install the package with `-e` (requires creating a `requirements.txt` file 😞 )) and I found out this message:

>  ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/docs/checkouts/readthedocs.org/user_builds/furo-humitos/checkouts/new-build-readthedocs
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.) 

(from https://readthedocs.org/projects/furo-humitos/builds/14891484/)
 
> Alternatively, a pre-install step on RTD would work.

This is not possible yet, but we have talk about this on https://github.com/readthedocs/readthedocs.org/pull/8190/files with the implementation of `build.jobs` in the config file. However, I don't really know _when_ that's going to be implemented due the work required.

> Yet-another alternative would be having Furo's build system generate the assets as part of the wheel generation process.

IMHO, this seems to make sense to me even _outside_ Read the Docs. Otherwise, building the package would be incomplete and end up with a broken package, right?

**Comment by pradyunsg** [comment]
> I didn't know that `pyproject.toml` does not support `-e` yet.

Heh, well, thankfully, give it a week or so -- I'm the release manager for pip 21.3, and that will bring support for editable installs for pyproject.toml projects (https://pip.pypa.io/en/latest/reference/build-system/pyproject-toml/#editable-installation).

**Comment by pradyunsg** [comment]
Closing this out, since this shouldn't be necessary with e62e08db20628af6f0e89d8c61e9c4fc91dfbcba. :)

**Pull request closed without merging**
