### PR TITLE
control maxdepth of the sidebar

### PR DESCRIPTION
**Pull request by hypc**

### CODE REVIEW

**Comment by pradyunsg** [comment]
Hi! Thanks for the PR!

Making the entire site structure visible in the sidebar was an intentional design choice, nudging documentation authors to avoid making deeply nested document hierarchies.

Is there any use case for hiding a part of the documentation from the user; and making it significantly more difficult to reach? Note that Furo is not intended to cover all potential site structures, and instead is (intentionally) biased toward small documentation sets.

**Comment by hypc** [comment]
I am automatically generating documentation for a project.
When there are more than 1000 files, the sidebar will exceed 200kb.

**Comment by pradyunsg** [comment]
Sorry, but a documentation site containing 1000s of pages is way too big to be using Furo with as-is. I don't want to add a configuration knob for such a usecase.

I recommend changing the elements using [the sidebar customisation options](https://pradyunsg.me/furo/customisation/sidebar/) for such use cases though. You should be able to customize this by overriding `sidebar/navigation.html`.

**Comment by abravalheri** [comment]
Hi @pradyunsg, would you reconsider reopening this PR? I have a different use case that might justify this change.

The use case is as follows:

In a nested page (not index.rst), I have a `toctree` that is being used to link implementation examples inside an specific section of the document. Please notice that this `toctree` does not refers to the global toc of the current page, but it is just used in a subsection, after an h2.

In the RTD theme, this is rendered as expected: the links in the toctree appear as children of the preceding h2 in the page, as you can see [here](https://pyscaffold.org/en/v4.0.2/extensions.html#examples):

RTD

However, since Furo omits nested titles on the left sidebar in favour of the menu on the right sidebar, something very weird happen: the preceding h2 ends up being shown on the right sidebar, while the links in the toctree are displayed on the left sidebar right under the h1. As a result the left sidebar is confusing because the h1 and the toctree links are not directly related. (You can see it [here](https://pyscaffold.org/en/change-docs-theme/extensions.html)

Furo

I was hoping that by using a maxdepth on the right sidebar I could simply hide the links of the toctree...
Is there any other way to get around this problem?
It seems to me that modifying the templates seem a bit too cumbersome to workaround a problem that is a direct consequence of splitting the menus between left and right...

**Pull request closed without merging**
