### PR TITLE
Replace domainindex.html with (more-or-less) the sphinx-doc/sphinx version

### PR DESCRIPTION
**Pull request by wlupton**
This is copied from https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/domainindex.html and then edited to extend base.html rather than layout.html.

I thought I'd already tried something similar to this, but obviously not!

This seems to work, but maybe further work is needed in order fully to integrate it into the theme.

### CODE REVIEW

**Comment by pradyunsg** [comment]
Oh hey, hi! I completely missed that this PR was filed!

Could you post a screenshot of how the generated index page looks, and possibly also provide some guidance on how to pages like that locally?

**Comment by wlupton** [comment]
Please see below for a couple of screenshots. The content is admittedly rather tightly on the left of the screen. As I mentioned, the only change from the original was to extend base.html rather than layout.html.

Sorry, what guidance were you asking for? Is there a missing "_create_" in "_guidance on how to pages like that locally_"? I don't believe that I've done anything special here.

If it works for you and results in non-empty module indexes then it's a step in the right direction, yes?

Screenshot 2021-03-20 at 09 28 04

Screenshot 2021-03-20 at 09 28 15

**Comment by pradyunsg** [comment]
Ah, this generates `py-modindex.html`.

**Comment by pradyunsg** [comment]
I guess what I'm asking is, how do I get my documentation to generate a `py-modindex` file?

**Comment by pradyunsg** [comment]
FWIW, while this is generally OK; I do think this need to use the same scaffolding as genindex.html, so that the generated page looks like https://pradyunsg.me/furo/genindex/ basically.

**Comment by wlupton** [comment]
> Ah, this generates `py-modindex.html`.

Yes. The context is in #50. The only reason that I knew to look at `domainindex.html` was because you said (in #50) that _someone needs to populate the domain index html template_!

> I guess what I'm asking is, how do I get my documentation to generate a `py-modindex file`?

AFAIK this is standard Sphinx. I think you just need this (pasted from #50) in your index file:

```
* :ref:`modindex`
```

> I do think this needs to use the same scaffolding as `genindex.html`, so that the generated page looks like https://pradyunsg.me/furo/genindex/ basically.

Fine! I've never written a Sphinx theme (and don't really want to learn). I just did something simple that seemed to improve the situation. I was rather hoping that you would take it from here. I don't know what has to be done to retain the sidebar.

Note: I noticed that there was a conflict because you've edited the same file, so I've rebased and re-pushed. The updated file is the same as before except that I've retained your extension of page.html rather than base.html. It doesn't make any difference to the look of the page (as far I can see).

**Comment by wlupton** [comment]
Ah, OK. I've struck out part of my previous comment.

I guess maybe all that is needed is to refer to the structure of `genindex.html` in updating `domainindex.html`. This shouldn't need any real knowledge of Sphinx or the template engine. I can have a go at doing this.

**Comment by pradyunsg** [comment]
Ah, no worries! Thanks for nudging on this. I'll probably find some existing Sphinx project with a domain index or two, and figure this out.

Feel free to close this PR, if you don't want to push this forward. That's perfectly fine! :)

**Comment by wlupton** [comment]
OK. I took a quick look (comparing with `genindex.html`) and noticed that it uses the `content` rather than the `body` block. Guessing that use of `body` was overriding something, I changed this to `content` and the module index now has the sidebar.

In fact it now looks quite like the main index, but the file itself still has a different structure (uses different variables etc.). I think that I will indeed bow out at this juncture. Please feel free to close this issue (thereby rejecting the PR).

One remark (which I could add to a new issue) is that I think it would be nice if there was a direct way of getting to the indices (and search page) from any page. I keep on finding myself going back to the main index page in order to get to them.

Thanks!

Screenshot 2021-03-20 at 17 18 59

**Comment by pradyunsg** [comment]
I ended up with 8b3325ea6986453bffd391b1a98f3d91bcb9af40, which is pretty nice overall; although some things are misaligned and shitz -- 80% there is better than not-there-because-going-for-perfect.

Thanks a lot for pushing this! ^>^

**Comment by wlupton** [comment]
NP. Thanks.

**Pull request closed without merging**
