### PR TITLE
Accessibility/search bar label

### PR DESCRIPTION
**Pull request by eviau-sat**
Hello :wave:

Here is a tiny PR addressing one change related to #93 : the search bar form.

I am not sure about the styling and what should be the placeholder now that we have a label. Suggestions welcome!

Screen capture:
furo_searchbar

### CODE REVIEW

**Comment by pradyunsg** [comment]
The change necessary here is adding an aria-label on the search input. Adding a `<label>` tag is not necessary.

**Comment by eviau-sat** [comment]
Thank you for the prompt reply for this tiny PR :) 

So, after doing a few searches, I feel that maybe this example from MDN is closer to what we would want for this search bar : [ARIA search role - MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role#examples)

I wanted to add a `<label>` tag because viewing the page on Firefox and running the accessibility tests gave me the following error : [Form elements should have a visible text label}(https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#form_elements_should_have_a_visible_text_label)

What do you think ?

**Comment by pradyunsg** [comment]
I think we should add an [aria-label](https://www.w3.org/TR/wai-aria/#aria-label) here and that is good-enough to handle the need for providing a text label. Adding `role="search"` would also be a good idea!

I tried looking at how [Wave](https://wave.webaim.org) and [LightHouse](https://developers.google.com/web/tools/lighthouse) evaluate the following, and as I expected, they're happy with it:

```diff
diff --git a/src/furo/theme/furo/sidebar/search.html b/src/furo/theme/furo/sidebar/search.html
index f7ca70e6..b1ff262f 100644
--- a/src/furo/theme/furo/sidebar/search.html
+++ b/src/furo/theme/furo/sidebar/search.html
@@ -1,5 +1,5 @@
 <form class="sidebar-search-container" method="get" action="{{ pathto('search') }}">
-  <input class="sidebar-search" placeholder={{ _("Search") }} name="q">
+  <input class="sidebar-search" placeholder={{ _("Search") }} name="q" aria-label="{{ _("Search" )}}">
   <input type="hidden" name="check_keywords" value="yes">
   <input type="hidden" name="area" value="default">
 </form>
```

The search icon provides sufficient context to visual users, and the aria-label would serve users who are navigating the page with a screen reader.

**Comment by pradyunsg** [comment]
> viewing the page on Firefox and running the accessibility tests gave me the following error : [Form elements should have a visible text label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#form_elements_should_have_a_visible_text_label)

FWIW, I just tried this out and also saw this. If I understand correctly though, it is a warning -- you'll notice that there are other situations on that page, where they use "must" instead of "should". :)

**Comment by eviau-sat** [comment]
I updated with the changes you suggested - we can always come back to it later if needed be I guess.

Let me know what you think!

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
Thanks @eviau-sat! ^>^

**Pull request merged**
