### PR TITLE
Show commit revision in footer.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by marxin** [comment]
May I please ping this?

**Comment by pradyunsg** [comment]
Is the `commit` context variable coming from RTD? Is there a specific reason to have it there, and are there any ways to achieve this without having a discrepancy between local builds vs RTD builds (I know, the edit button is a weird one + footer icons are a bit weird, but they fill what would otherwise be voids — this adds additional content to something that already has content)

**Comment by marxin** [comment]
No, it comes from `conf.py` where one can define it without RTD:
```python3
html_context = {
    'commit': __get_git_revision ()
}
```

That's how I use it w/o RTD.

**Comment by pradyunsg** [comment]
Right, I don’t think users should need to set html_context to use a Sphinx theme — that’s exposing too many details.

**Comment by marxin** [comment]
All right. Do you see any other way we can have a customizable footer in Furo?

**Comment by marxin** [comment]
May I please remind this?

**Pull request closed without merging**
