### PR TITLE
Section permalinks: fix hover styling

### PR DESCRIPTION
**Pull request by ferdnyc**
- Remove `text-decoration` from the permalink icons, because it's barely visible and looks odd.
- To ensure they still have some hover-responsiveness, define a new brand color (`--color-brand-highlight`) — which in the default themes is simply `--color-brand-content` with the `L` value dialed up a bunch in the HSL colorspace — and set it as the permalink hover color.
- Also override visited-link coloring from permalinks, as a special case, and have them always use the brand-content / brand-highlight color.

#### Additional info

This was inspired by the fact that every time I hover over a section title, the section link icon appears, accompanied by a tiny dot in the lower-left corner that gets marginally more visible when the icon is hovered over. It took me forever to figure out that it even _**was**_ the tiny bit of the text-decoration-line that's actually visible around the icon's descender. But once I did work that out, it seemed really pointless for it to be there, doing nothing useful.

Adding an additional brand color is a _big_ flex just for this tiny feature, I realize. Alternatives would be to have the permalink icon hover to the text color, or to reverse that and have it initially appear text-colored, but hover to link color. I didn't try either of those, but they're options if adding the "special" highlight color seems too drastic.

Regarding the visited-link override: I normally _hate_ when sites disable visited-link coloring, and will typically userstyle it back in with extreme prejudice. But I didn't want to have to define a _second_ highlight color for the permalink hovers when they're also visited links, and permalinks are enough of a special case that I think not having them turn purple when used seems valid.

### CODE REVIEW

**Comment by ferdnyc** [comment]
Oh, this PR branch also includes my fix from #812, since I needed it to get the linter to pass. But presumably that'll be merged before this.

**Comment by ferdnyc** [comment]
They really shouldn't be referred to as permalinks, because they're _not_, they're merely section links. But they were called that way in the code, so now I've started doing it too.

Worse, I named the new variables `--color-permalink-*`, which in retrospect was a poor choice. I can change that in this PR, or even scrub the term 'permalink' from the code entirely, if anyone feels strongly enough about it.

**Comment by ferdnyc** [comment]
Screencasts demonstrating the change, in both themes, converted to animated GIF courtesy of ezgif.com:

### Before
FuroLinks-Before

### After
FuroLinks-After

**Comment by pradyunsg** [comment]
> Remove `text-decoration` from the permalink icons, because it's barely visible and looks odd.

This is platform-specific and depends on the fonts available on the system being used. My guess is that you're on a Linux host where it's falling back to a font with a really tall symbol for that character.

https://github.com/pradyunsg/furo/assets/3275593/8cfc3d26-5362-4bf8-adb0-284e77769d85

I don't think permalinks should be special-cased as done in this PR though, since they're still links.

**Comment by ferdnyc** [comment]
You're definitely right about it being platform-specific... here's how things look on Android, I just discovered:



On the bright side, you do see more of the underline decoration...

**Comment by ferdnyc** [comment]
Well, the Android thing is still somewhat concerning, and I do think the hover response of section links could be improved, but this doesn't seem to be the way to do it. Closing.

**Pull request closed without merging**
